Repository DeliveryAPP-Project/delivery-app-backend, pull requests merged in 2025-03, with the labels that each got.

#57 Feat/api lead cadastro
  .python-version
  migrations/versions/0c829e8d9b27_.py
  migrations/versions/d0ac4acff526_.py
  project/controller/client_controller.py
  project/controller/lead_controller.py
  project/controller/order_controller.py
  project/controller/product_controller.py
  project/controller/restaurant_controller.py
  project/controller/user_controller.py
  project/doc_model/doc_models.py
  project/ext/restapi/__init__.py
  project/models/lead_model.py
  project/service/lead_service.py
  project/utils/namespace.py
  requirements.txt
  settings.toml
  tests/test_lead.py
Labels: enhancement

#60 Feat/scrum 75 refatoracao do codigo para substituir api efipay
  .secrets-example.toml
  certificate_pix/certificate.pem
  migrations/versions/0721af649c52_.py
  migrations/versions/c04ce36db125_.py
  migrations/versions/ff5f56fb7a3c_.py
  migrations/versions/fff14b8641de_initial_migration.py
  project/base.py
  project/controller/client_controller.py
  project/controller/lead_controller.py
  project/controller/order_controller.py
  project/controller/payment_controller.py
  project/controller/product_controller.py
  project/controller/restaurant_controller.py
  project/controller/user_controller.py
  project/doc_model/doc_models.py
  project/errors/NotFoundErr.py
  project/ext/database.py
  project/ext/payment_gateways/mercadopago/__init__.py
  project/ext/payment_gateways/mercadopago/main.py
  project/ext/payment_gateways/mercadopago/payment.py
  project/ext/payment_gateways/mercadopago/schema.py
  project/ext/restapi/__init__.py
  project/ext/serializer.py
  project/models/__init__.py
  project/models/client_model.py
  project/models/order_model.py
  project/models/payment_model.py
  project/models/pix_model.py
  project/service/order_service.py
  project/service/payment_service.py
  project/utils/calculate_total.py
  project/utils/constants_pix.py
  project/utils/generate_unique_txid.py
  project/utils/namespace.py
  project/utils/pix_utils.py
  requirements.txt
  settings.toml
  tests/conftest.py
  tests/test_client.py
  tests/test_main.py
  tests/test_order.py
  tests/test_payment.py
  tests/test_product.py
  tests/test_restaurant.py
Labels: enhancement

#61 fix: rm .secrets from gitignore due to bug on enviroment
  .gitignore
  .secrets.toml
Labels: bug

#62 Fix/dockerfile to build
  .dockerignore
  docker-compose.ext.yml
  docker-compose.yml
  migrations/versions/7bc0658e9c3d_init_migrate.py
  migrations/versions/d0ac4acff526_.py
  migrations/versions/fff14b8641de_initial_migration.py
Labels: bug

#68 FIX: Enhance CORS configuration to restrict origins for API endpoints
  project/base.py
Labels: bug

#70 FIX: Remove trailing slash from CORS configuration for local development
  project/base.py
Labels: bug

#75 Refactor base.py to remove unused CORS preflight handling and example…
  project/base.py
Labels: invalid

#76 Feature/scrum 79 refatoracao tabela estabelecimentos
  README.md
  migrations/versions/9255441d2a22_.py
  project/controller/establishment_controller.py
  project/controller/restaurant_controller.py
  project/doc_model/doc_models.py
  project/ext/commands.py
  project/ext/restapi/__init__.py
  project/ext/serializer.py
  project/models/__init__.py
  project/models/establishment_model.py
  project/models/mock_data.py
  project/models/order_model.py
  project/models/product_model.py
  project/models/restaurant_model.py
  project/service/establishment_service.py
  project/service/order_service.py
  project/service/restaurant_service.py
  project/utils/namespace.py
  project/utils/twilio_utils.py
  scripts/populate_database.py
  tests/conftest.py
  tests/test_establishment.py
  tests/test_order.py
  tests/test_product.py
  tests/test_restaurant.py
Labels: enhancement
